version: '3'

services:
  test_database:
    container_name: test_database
    image: 'mysql:8.0.22'
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '3308:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=quest_middleware_database_test
    tmpfs: /var/lib/mysql
  database:
    image: 'mysql:8.0.22'
    command: --default-authentication-plugin=mysql_native_password
    container_name: database
    ports:
      - '3307:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=quest_middleware_database
    volumes:
      - p3-db:/var/lib/mysql
  server_middleware:
    container_name: server_middleware
    depends_on:
      - database
    build: '.'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - DB_USER=root
      - DB_PASS=root
      - DB_NAME=quest_middleware_database
      - DB_HOST=database
      - DB_PORT=3306
    ports:
      - '5000:5000'
    command: 'bash -c "chmod u+x ./scripts/wait-for-it.sh && ./scripts/wait-for-it.sh db:3306 && npm run start:watch"'

volumes:
  p3-db:
